# Generated by Django 4.0 on 2021-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(blank=True, default='https://i.imgur.com/rCtiN2c.png', null=True),
        ),
    ]
